#!/usr/bin/env bash

# Menampilkan route dan mendapatkan IP Gateway
echo "Menampilkan route..."
ip route

# Menentukan IP Gateway (default route)
gateway_ip=$(ip route | grep default | awk '{print $3}')

# Menampilkan IP Gateway yang ditemukan
echo "IP Gateway yang ditemukan: $gateway_ip"

# Menghubungkan ke perangkat menggunakan ADB
echo "Menghubungkan ke perangkat ADB..."
adb connect "$gateway_ip":3055

echo "Selesai!"
